# ########################
# Environment variables  #
# ########################
#
export EDITOR=nvim
export PAGER=less

# remove duplicate entried from $PATH 
# since zsh has a $path array to manupilate all paths
typeset -U PATH path

export MANPATH="/usr/local/man:$MANPATH"
# export XDG_CONFIG_HOME="$HOME/voidrice/.config/"
export PATH=$HOME/.local/bin:$PATH
# export ZDOTDIR=$HOME/projects/voidrice/.config

# user compiled python as default python
export PATH=$HOME/python/bin:$PATH
export PYTHONPATH=$HOME/python/

# user installed node as default node
export PATH="$HOME/node/node-v14.16.0-linux-x64"/bin:$PATH
export NODE_MIRROR=https://mirrors.ustc.edu.cn/node/
	

source "$HOME/.cargo/env"
