###########################
# Zshrc 0.0.1
# by Errelin
###########################


# prompt
if [ $(whoami) = 'leon' ]; then
	PROMPT=' %F{green}%~ %f'
else
	PROMPT='%F{red}%n%f %~ '
fi

# export MANPATH="/usr/local/man:$MANPATH"
#export XDG_CONFIG_HOME="$HOME/voidrice/.config/"
export PATH=$HOME/.local/bin:$PATH

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
#
# Utilities
alias sx="startx"

# open programms
alias v="nvim"
alias n="nvim"
alias rr="ranger"
alias em="emacs -nw"
# pacman or xbps
if [ -d /etc/xbps.d ]; then
		alias ins="sudo xbps-install -S"
		alias upd="sudo xbps-install -Sy"
		alias unins="sudo xbps-remove -R"
		alias sch="xbps-query -R"
		alias lpk="xbps-query -l"
		alias br="brightnessctl -d intel_backlight s +10%"
		alias dr="brightnessctl -d intel_backlight s 10%-"

fi

if [ -d /etc/pacman.d ]; then
		alias ins="sudo pacman -S"
		alias upd="sudo pacman -Sy"
		alias unins="sudo pacman -Rns"
		alias sch="pacman -Ss"
		alias lpk="pacman -Qi"
		alias br="xbacklight -inc 10"
		alias dr="xbacklight -dec 10"
fi

# open, source dotfiles 
alias nz="nvim ~/.zshrc"
alias sz="source ~/.zshrc"
alias nr="nvim ~/.config/nvim/init.vim"
alias nvr="nvim ~/.vimrc"

# cmd shorthands
alias ll="ls -al"
alias logout="pkill -KILL -u leon"

# git
alias pa="git push origin main"


# texlive
alias tlmgr='/usr/share/texmf-dist/scripts/texlive/tlmgr.pl --usermode' 


# emacs
alias emacs="emacs -nw"

# dropbox
alias dropsync="dropbox.py start"
alias dropshut="dropbox.py stop"
alias dropst="dropbox.py status"
