#!/bin/sh

# start the D-Bus session bus before Fcitx starts.
# eval "$(dbus-launch --sh-syntax --exit-with-session)"

userresources=$HOME/.Xresources
sysresources=/etc/X11/xinit/.Xresources

# merge in defaults
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
    xrdb -merge -I$HOME "$userresources"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Auto repeat freq
xset r rate 400 100

# fcitx5
fcitx5 &

# redshift
#redshift &

# wm
# exec awesome

exec startxfce4
# exec mate-session
