#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

    xrdb -merge -I$HOME "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# add font paths for X server
xset +fp /home/errenil/.local/share/fonts/


# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# fcitx5
# export GTK_IM_MODULE=fcitx
# export QT_IM_MODULE=fcitx
# export XMODIFIERS=@im=fcitx

# Compositor
picom --config ${HOME}/projects/voidrice/.config/picom/picom.conf &

if [[ "$(hostname)" == "gohan" ]] ; then
	source ${HOME}/projects/voidrice/.config/x11/gohan
elif [[ "$(hostname)" == "goku" || "$(hostname)" == "near" ]] ; then
	source ${HOME}/projects/voidrice/.config/x11/goku
fi
