#
# ~/.bash_profile
#

# Set up PS1, alias, and user-defined fns
# Can also be sourced at the end of .bash_profile
[[ -f ~/.bashrc ]] && . ~/.bashrc


# env vars
export XDG_CONFIG_HOME="$HOME/.config"
export PATH="$HOME/.local/bin:$PATH"
export PROJECTS_HOME="$HOME/projects"

# see https://docs.npmjs.com/cli/v6/using-npm/config#npmrc-files
export NPM_CONFIG_USERCONFIG=$HOME/.config/npm/npmrc

# source node path only when node was installed under $HOME/node
[[ ! -x /usr/local/bin/node ]] && [[ -d $HOME/node ]] && \
    export PATH="$HOME/node/node-v16.13.0-linux-x64/bin:$PATH"

# TexLive
TEX_VERSION=2021
[[ -d $HOME/texlive/${TEX_VERSION} ]] && \
    { export TEXLIVE_HOME="$HOME/texlive/${TEX_VERSION}/bin/x86_64-linux"
      export TEXLIVE_MAN="$HOME/texlive/${TEX_VERSION}/texmf-dist/doc/man"
      export TEXLIVE_INFO="$HOME/texlive/${TEX_VERSION}/texmf-dist/doc/info"
      export PATH="$TEXLIVE_HOME:$PATH"
      export MANPATH="$TEXLIVE_MAN:$MANPATH"
      export INFOPATH="$TEXLIVE_INFO:$INFOPATH"
    }

export PATH="$HOME/.local/solana-release/bin:$PATH"

# source  cargo path only when rust was installed under $HOME
[[ ! -x /usr/bin/cargo ]] && [[ -d $HOME/.cargo ]] && . "$HOME/.cargo/env"
