#!/usr/bin/env sh

# Sync my dot files

declare -a apps
declare -a themes
apps=(lf npm git nix tmux foot sway helix ctags river sway swaylock waybar gammastep zellij environment.d)
themes=(chacha ft carbon rustdoc)

dst="${HOME}/.config"
src="${HOME}/projects/voidrice/.config"
esrc="${HOME}/projects/emacs.d"
etheme="${HOME}/projects/emacs-themes"
edst="${HOME}/.emacs.d"
remote="git@github.com:Linerre"

# When this fn runs, the src dir must have already existed
function process_apps() {
    if [ ! -d ${dst} ] ; then
	    echo "${HOME}/.config does not exist; creating it ..."
	    mkdir ${dst}
    fi

    for a in "${apps[@]}"; do
	    if [ -d "${dst}/${a}" ] ; then
	        echo "Skipping $a as it exits ..."
	    else
	        echo "Creating symlink for $a ..."
	        ln -s "${src}/${a}" "${dst}/${a}"
	    fi
    done
}


function sync_emacs() {
    if [ -h ${edst} ] ; then
	    echo "Skipping ${edst} as it already exists ..."
    elif [ -d ${edst} ] ; then
	    echo "Erasing current emacs.d to make a new one ..."
	    rm -rf ${edst}
    fi
    echo "Creating symlink for emacs.d ..."
    ln -s ${esrc} ${edst}

}



function process_emacs() {
    if [ ! -d ${esrc} ] ; then
	    echo "${esrc} does NOT exist. Did you forget to pull it?"
	    echo "Pulling emacs.d from ${remote}"
	    git clone "${remote}/emacs.d.git" "${HOME}/projects/emacs.d"
    fi
	sync_emacs
}


function pull_themes() {
    local td="${HOME}/projects/emacs-themes"
    [[ ! -d  ${td} ]] && mkdir -p ${td}
    cd ${td}
    for t in "${themes[@]}" ; do
	    case $t in
	        chacha | ft | rustdoc )
		        git clone "${remote}/${t}-theme.git"
		        ;;
	        carbon )
		        git clone https://github.com/DogLooksGood/carbon-theme.git
		        ;;
	        *)
		        echo "Unknown theme $t"
	    esac
    done
}

function process_themes() {
    if [ ! -d ${etheme} ] ; then
	    echo "${etheme} does NOT exist. Did you pull the themes?"
	    echo "Start pulling themes ..."
	    pull_themes
    fi

    cd ${edst}/themes

    for t in $(ls ${etheme}) ; do
	    case $t in
	        chacha-theme | ft-theme | carbon-theme )
		        if [ -h "${edst}/themes/${t}.el" ] ; then
		            echo "Skipping $t as it already symlinked ..."
		        else
		            echo "Creating symlinks for $t ..."
		            ln -s "${etheme}/${t}/${t}.el" "${t}.el"
		        fi
		        ;;
	        rustdoc-theme )
		        if [ -h "${edst}/themes/rustdoc-dark-theme.el" ] ; then
		            echo "Skipping $t as it already symlinked ..."
		        else
		            echo "Creating symlinks for $t ..."
		            ln -s "${etheme}/${t}/rustdoc-dark-theme.el" "rustdoc-dark-theme.el"
	        fi
		        ;;
	        *)
		        echo "Skipping theme $t ..."
		        ;;
	    esac
    done
}

function process_shell() {
    cd
    if [ $(basename ${SHELL}) == bash ] ; then
        if [ -h ${HOME}/.bashrc ] || [ -f ${HOME}/.bashrc ] ; then
            echo "Removing current .bashrc ..."
            rm -f ${HOME}/.bashrc
        fi

        if [ -h ${HOME}/.bash_profile ] || [ -f ${HOME}/.bash_profile ] ; then
            echo "Removing current .bash_profile ..."
            rm -f ${HOME}/.bash_profile
        fi

        echo "Creating symlink for .bash_profile and .bashrc ..."
        ln -s ${src}/shells/bashrc ${HOME}/.bashrc
        ln -s ${src}/shells/bash_profile ${HOME}/.bash_profile

        if [[ $0 == -* ]] ; then
            source ${HOME}/.bash_profile
        else
            source ${HOME}/.bashrc
        fi

    elif [ $(basename ${SHELL}) == zsh ] ; then
        if [ -h ${HOME}/.zshrc ] || [ -f ${HOME}/.zshrc ] ; then
            echo "Removing current .zshrc ..."
            rm -f ${HOME}/.zshrc
        fi

        if [ -h ${HOME}/.zprofile ] || [ -f ${HOME}/.zprofile ] ; then
            echo "Removing current .zprofile ..."
            rm -f ${HOME}/.zprofile
        fi

        echo "Creating symlink for .zprofile and .zshrc ..."
        ln -s ${src}/shells/zshrc ${HOME}/.zshrc
        ln -s ${src}/shells/zprofile ${HOME}/.zprofile
        if [[ $0 == -* ]] ; then
            source ${HOME}/.zprofile
        else
            source ${HOME}/.zshrc
        fi
    fi
}


process_apps
process_emacs
process_themes
process_shell
